//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSinhVien.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLSinhVienEntities : DbContext
    {
        public QLSinhVienEntities()
            : base("name=QLSinhVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiemSV> DiemSVs { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<LopHocPhan> LopHocPhans { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<vDiem> vDiems { get; set; }
        public virtual DbSet<vDiemTheoMon> vDiemTheoMons { get; set; }
        public virtual DbSet<vDiemTheoSV> vDiemTheoSVs { get; set; }
        public virtual DbSet<vLopHocPhan> vLopHocPhans { get; set; }
        public virtual DbSet<vSinhVien> vSinhViens { get; set; }
    
        public virtual ObjectResult<p_DauRot_Result> p_DauRot()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_DauRot_Result>("p_DauRot");
        }
    
        public virtual ObjectResult<p_findGiangVien_Result> p_findGiangVien(string find)
        {
            var findParameter = find != null ?
                new ObjectParameter("find", find) :
                new ObjectParameter("find", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_findGiangVien_Result>("p_findGiangVien", findParameter);
        }
    
        public virtual ObjectResult<p_findSinhVien_Result> p_findSinhVien(string find)
        {
            var findParameter = find != null ?
                new ObjectParameter("find", find) :
                new ObjectParameter("find", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_findSinhVien_Result>("p_findSinhVien", findParameter);
        }
    
        public virtual ObjectResult<p_findTheoKhoa_Result> p_findTheoKhoa(string khoa)
        {
            var khoaParameter = khoa != null ?
                new ObjectParameter("khoa", khoa) :
                new ObjectParameter("khoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_findTheoKhoa_Result>("p_findTheoKhoa", khoaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> p_ktGVTrungLich(Nullable<int> thu, Nullable<System.DateTime> ngayBD, Nullable<System.DateTime> ngayKT, Nullable<int> tietBD, Nullable<int> tietKT, string maGV)
        {
            var thuParameter = thu.HasValue ?
                new ObjectParameter("thu", thu) :
                new ObjectParameter("thu", typeof(int));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("ngayBD", ngayBD) :
                new ObjectParameter("ngayBD", typeof(System.DateTime));
    
            var ngayKTParameter = ngayKT.HasValue ?
                new ObjectParameter("ngayKT", ngayKT) :
                new ObjectParameter("ngayKT", typeof(System.DateTime));
    
            var tietBDParameter = tietBD.HasValue ?
                new ObjectParameter("tietBD", tietBD) :
                new ObjectParameter("tietBD", typeof(int));
    
            var tietKTParameter = tietKT.HasValue ?
                new ObjectParameter("tietKT", tietKT) :
                new ObjectParameter("tietKT", typeof(int));
    
            var maGVParameter = maGV != null ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("p_ktGVTrungLich", thuParameter, ngayBDParameter, ngayKTParameter, tietBDParameter, tietKTParameter, maGVParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> p_ktPHTrungLich(Nullable<int> thu, Nullable<System.DateTime> ngayBD, Nullable<System.DateTime> ngayKT, Nullable<int> tietBD, Nullable<int> tietKT, string phong)
        {
            var thuParameter = thu.HasValue ?
                new ObjectParameter("thu", thu) :
                new ObjectParameter("thu", typeof(int));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("ngayBD", ngayBD) :
                new ObjectParameter("ngayBD", typeof(System.DateTime));
    
            var ngayKTParameter = ngayKT.HasValue ?
                new ObjectParameter("ngayKT", ngayKT) :
                new ObjectParameter("ngayKT", typeof(System.DateTime));
    
            var tietBDParameter = tietBD.HasValue ?
                new ObjectParameter("tietBD", tietBD) :
                new ObjectParameter("tietBD", typeof(int));
    
            var tietKTParameter = tietKT.HasValue ?
                new ObjectParameter("tietKT", tietKT) :
                new ObjectParameter("tietKT", typeof(int));
    
            var phongParameter = phong != null ?
                new ObjectParameter("Phong", phong) :
                new ObjectParameter("Phong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("p_ktPHTrungLich", thuParameter, ngayBDParameter, ngayKTParameter, tietBDParameter, tietKTParameter, phongParameter);
        }
    
        public virtual ObjectResult<p_svLopHocPhan_Result> p_svLopHocPhan(string maLopHP)
        {
            var maLopHPParameter = maLopHP != null ?
                new ObjectParameter("MaLopHP", maLopHP) :
                new ObjectParameter("MaLopHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_svLopHocPhan_Result>("p_svLopHocPhan", maLopHPParameter);
        }
    }
}
