//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSinhVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLopHocPhan
    {
        public string MaLopHocPhan { get; set; }
        public string TenLopHoc { get; set; }
        public string TenMon { get; set; }
        public string PhongHoc { get; set; }
        public int HocKy { get; set; }
        public string TenGV { get; set; }
        public int Thu { get; set; }
        public System.DateTime NgayBD { get; set; }
        public System.DateTime NgayKT { get; set; }
        public int TietBD { get; set; }
        public int TietKT { get; set; }
        public string LoaiLop { get; set; }
    }
}
