//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSinhVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSinhVien
    {
        public string MaSV { get; set; }
        public string HoTenSV { get; set; }
        public string Lop { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public System.DateTime NgayNhapHoc { get; set; }
        public string GioiTinh { get; set; }
    }
}
